# Generated by Django 6.0.7 on 2026-07-22 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveEntry',
            fields=[
                ('leave_id', models.AutoField(db_column='leave_id', primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField(db_column='emp_id')),
                ('leave_duration', models.CharField(choices=[('Single Day', 'Single Day'), ('Multiple Day', 'Multiple Day')], db_column='leave_duration', max_length=20)),
                ('leave_type', models.CharField(choices=[('OD', 'OD'), ('Casual Leave', 'Casual Leave'), ('Loss Of Pay', 'Loss Of Pay')], db_column='leave_type', max_length=20)),
                ('single_leave_date', models.DateField(blank=True, db_column='single_leave_date', null=True)),
                ('session', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM'), ('Both', 'Both')], db_column='session', max_length=10, null=True)),
                ('from_date', models.DateField(blank=True, db_column='from_date', null=True)),
                ('to_date', models.DateField(blank=True, db_column='to_date', null=True)),
                ('reason', models.TextField(db_column='reason')),
                ('alternate_employee_id', models.IntegerField(blank=True, db_column='alternate_employee_id', null=True)),
                ('leave_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_column='leave_status', default='Pending', max_length=20)),
            ],
            options={
                'db_table': 'leave_entry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkArrangement',
            fields=[
                ('arrangement_id', models.AutoField(db_column='arrangement_id', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], db_column='status', default='Pending', max_length=20)),
                ('response_date', models.DateTimeField(blank=True, db_column='response_date', null=True)),
                ('remarks', models.CharField(blank=True, db_column='remarks', max_length=255)),
                ('leave', models.ForeignKey(db_column='leave_id', on_delete=django.db.models.deletion.CASCADE, to='leave_management.leaveentry')),
            ],
            options={
                'db_table': 'work_arrangement',
            },
        ),
    ]
